---
title: "Assignment 3"
output: html_document
---


```{r}
library(rio)
Pollution_index=import("Pollution index.xlsx")
str(Pollution_index)
```
```{r}
boxplot(Pollution_index[,c('particlePollution','pop2022')])
```

```{r}
clustData=Pollution_index #copy
```

```{r}
clustData[,-1]=lapply(clustData[,-1], scale)
clustData[,-1]=as.data.frame(clustData[,-1])
```


```{r}
#trying standardization
clustData$particlePollution=as.vector(clustData$particlePollution)
clustData$pop2022=as.vector(clustData$pop2022)

```

```{r}
str(clustData[,-1])
```

```{r}

set.seed(123)
library(cluster)
#vars=c('particlePollution_S')#variables needed

distMatrix=cluster::daisy(clustData[,-1])
        
res.pam=cluster::pam(x=distMatrix,
                     k = 3,
                     cluster.only = F)
clustData$cluster=as.factor(res.pam$clustering)

##ERROR 
theVars=c('particlePollution_S','cluster')
aggregate(.~cluster,
          data=Pollution_index[,theVars],
          FUN=median)
Pollution_index$cluster=factor(Pollution_index$cluster,
                           levels=c(1,3,2),
                           labels=c("low","mid","best"), 
                           ordered=T)
```

```{r}
linkmap=("https://github.com/Rao-Anand/Assignment-3/blob/main/worldMap.geojson")

library(sf)

mapWorld=read_sf("worldMap.geojson")
head(mapWorld)

```
```{r}
merge(mapWorld,
                   clustData,by.x='NAME',by.y='country')
```

```{r}

mapWorldVars=merge(mapWorld,
                   clustData,by.x='NAME',by.y='country')


library(ggplot2)
# plot original map
base=ggplot(data=mapWorld) + geom_sf(fill='grey90',
                                     color=NA) + theme_classic()
```




```{r}
base #base map

colMap= base + geom_sf(data=mapWorldVars,
                       aes(fill=particlePollution),
                       color=NA)
colMap
```

```{r}
colMap + scale_fill_gradient(low = 'red',
                             high= 'blue')

clusterMap= base + geom_sf(data=mapWorldVars,
                           aes(fill=cluster),
                           color=NA) # color of border
clusterMap 

clusterMap+ scale_fill_brewer(palette ='YlOrRd')


#previously
theLegLabels=c('1_worst',2,'3_best')
theLegTitle="World_Order\n(grey is missing)"

#now
clusterMap+ scale_fill_brewer(palette ='YlOrRd',
                              direction = -1, # color order
                              labels=theLegLabels,
                              name=theLegTitle)


```

